# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField(blank=True, null=True)),
                ('room_name', models.CharField(blank=True, max_length=64, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('total_box_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'building_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=64, null=True)),
                ('major', models.CharField(blank=True, max_length=64, null=True)),
                ('total_box', models.IntegerField(blank=True, null=True)),
                ('activate_box', models.IntegerField(blank=True, null=True)),
                ('unactivate_box', models.IntegerField(blank=True, null=True)),
                ('unuse_box', models.IntegerField(blank=True, null=True)),
                ('room_usage', models.DecimalField(blank=True, decimal_places=4, max_digits=64, null=True)),
                ('check_box_power', models.IntegerField(blank=True, null=True)),
                ('design_box_power', models.IntegerField(blank=True, null=True)),
                ('sign_box_power', models.IntegerField(blank=True, null=True)),
                ('destribute_box_power', models.IntegerField(blank=True, null=True)),
                ('sign_box_power_usage', models.DecimalField(blank=True, decimal_places=4, max_digits=64, null=True)),
                ('room_id', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'device_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Electricbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(blank=True, max_length=20, null=True)),
                ('box_id', models.IntegerField(blank=True, max_length=20, null=True)),
                ('device_room', models.CharField(blank=True, max_length=64, null=True)),
                ('box_name', models.CharField(blank=True, max_length=64, null=True)),
                ('client_name', models.CharField(blank=True, max_length=64, null=True)),
                ('power_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True)),
                ('threshold_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True)),
                ('on_state_date', models.DateTimeField(blank=True, null=True)),
                ('power_on_date', models.DateTimeField(blank=True, null=True)),
                ('down_power_date', models.DateTimeField(blank=True, null=True)),
                ('device_num', models.IntegerField(blank=True, null=True)),
                ('device_u_num', models.IntegerField(blank=True, null=True)),
                ('box_type', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'electricbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentCabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_name', models.CharField(max_length=64)),
                ('power', models.IntegerField(max_length=64)),
            ],
            options={
                'db_table': 'equipment_cabinet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxid', models.IntegerField(blank=True, max_length=64, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('level', models.IntegerField(blank=True, max_length=64, null=True)),
                ('clock', models.IntegerField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'history_power',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IDCBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_id', models.IntegerField(blank=True, null=True)),
                ('building_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'idc_building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('attribute', models.CharField(blank=True, max_length=64, null=True)),
                ('electric_cap', models.IntegerField(blank=True, max_length=64, null=True)),
                ('power', models.IntegerField(blank=True, max_length=64, null=True)),
                ('usage_power', models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True)),
                ('total_box', models.IntegerField(blank=True, max_length=64, null=True)),
                ('built', models.IntegerField(blank=True, max_length=64, null=True)),
                ('activate', models.IntegerField(blank=True, max_length=64, null=True)),
                ('unactivate', models.IntegerField(blank=True, max_length=64, null=True)),
                ('usage_box', models.DecimalField(blank=True, decimal_places=4, max_digits=64, null=True)),
                ('remark', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'industry_park',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField(blank=True, null=True)),
                ('on_state_date', models.DateTimeField(blank=True, null=True)),
                ('power_on_date', models.DateTimeField(blank=True, null=True)),
                ('down_power_date', models.DateTimeField(blank=True, null=True)),
                ('device_num', models.IntegerField(blank=True, null=True)),
                ('start_u_num', models.IntegerField(blank=True, null=True)),
                ('end_u_num', models.IntegerField(blank=True, null=True)),
                ('total_u_num', models.IntegerField(blank=True, null=True)),
                ('device_code', models.CharField(blank=True, max_length=64, null=True)),
                ('device_type', models.CharField(blank=True, max_length=64, null=True)),
                ('device_status', models.CharField(blank=True, max_length=64, null=True)),
                ('power_num', models.CharField(blank=True, max_length=64, null=True)),
                ('device_alternating', models.CharField(blank=True, max_length=64, null=True)),
                ('device_threshold_rt', models.DecimalField(blank=True, decimal_places=4, max_digits=64, null=True)),
            ],
            options={
                'db_table': 'network_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OverRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_room', models.CharField(blank=True, max_length=64, null=True)),
                ('box_name', models.CharField(blank=True, max_length=64, null=True)),
                ('client_name', models.CharField(blank=True, max_length=64, null=True)),
                ('power_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('avg_power_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('month', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'over_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QRIDCRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'qridc_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelectBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(blank=True, max_length=20, null=True)),
                ('box_type', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'select_box',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(max_length=20)),
                ('tab_id', models.IntegerField(max_length=20)),
            ],
            options={
                'db_table': 'threshold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'file_name',
            },
        ),
    ]
